package view;

import client.RMIClientManager;
import service.CustomerService;
import util.ValidationUtil;
import util.ValidationUtil.ValidationResult;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Employee;

/**
 *
 * @author andyb
 */
public class CustomerPanel extends javax.swing.JPanel {
    private CustomerService customerService;
    
    private DefaultTableModel tblModel = new DefaultTableModel();
    private Employee currentEmployee;
    private SalesPanel salesPanel;
    private boolean isCashierMode = false;

    /**
     * Creates new form ProductsPanel
     */
    public CustomerPanel(SalesPanel panel, Employee employee) {
        this.currentEmployee = employee;
        this.salesPanel = panel;
        
        initComponents();
        
        try{
            customerService = RMIClientManager.getInstance().getCustomerService();
        } catch(Exception e){
            e.printStackTrace();
        }
        
        constructTableColumns();
        retrieveDataFromDB();
        
    }
    
    public void setCashierMode(boolean isCashier){
        this.isCashierMode = isCashier;
        
        btnAdd.setEnabled(true);
        btnUpdate.setEnabled(true);
        btnDelete.setEnabled(false);
        btnSearch.setEnabled(true);
        
        btnDelete.setBackground(new Color(100,100,100));
        btnDelete.setToolTipText("Delete Customer - Admin Only");
    }
    
    public void setAdminMode(boolean isAdmin){
        if(isAdmin){
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnSearch.setEnabled(true);
        }
    }
    
    private void constructTableColumns(){
        tblModel.addColumn("Customer ID");
        tblModel.addColumn("Full Name");
        tblModel.addColumn("Adress");
        tblModel.addColumn("E-Mail");
        tblModel.addColumn("Phone Number");
        tblModel.addColumn("Registration Date");
        customerTable.setModel(tblModel);
    }
    
    private void retrieveDataFromDB(){
        tblModel.setRowCount(0);
        
        try{
            List<Customer> customers = customerService.findAllCustomers();
            
            if(customers != null){
                for(Customer customer : customers){
                    tblModel.addRow(new Object[]{
                        customer.getCustomerId(),
                        customer.getFullName(),
                        customer.getAddress(),
                        customer.getEmail(),
                        customer.getPhone(),
                        customer.getRegistrationDate()
                    });
                }
            }
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void refresh(){
        txtCustomerName.setText("");
        txtEmail.setText("");
        txtPhoneNumber.setText("");
        txtAddress.setText("");
        txtSearch.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtPhoneNumber = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel5.setBackground(new java.awt.Color(50, 50, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Customer Management");

        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(160, 160, 160));
        jLabel10.setText("Customer Name");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(160, 160, 160));
        jLabel11.setText("Address");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(160, 160, 160));
        jLabel13.setText("Email");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(160, 160, 160));
        jLabel14.setText("Phone Number");

        btnAdd.setBackground(new java.awt.Color(34, 197, 94));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(59, 130, 246));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(239, 68, 68));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(txtPhoneNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(txtAddress))
                .addGap(18, 18, 18))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(customerTable);

        btnSearch.setBackground(new java.awt.Color(100, 100, 100));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(240, 240, 240));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(160, 160, 160));
        jLabel1.setText("Search By ID");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText().trim();
        
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Customer ID");
        if(!ValidationUtil.validateAndShow(this, idValidation)){
            txtSearch.requestFocus();
            return;
        }
        
        int customerId = Integer.parseInt(searchStr);
        
        try{
            Customer foundCustomer = customerService.findCustomerById(customerId);
            
            if(foundCustomer != null){
                txtCustomerName.setText(foundCustomer.getFullName());
                txtEmail.setText(foundCustomer.getEmail());
                txtPhoneNumber.setText(foundCustomer.getPhone());
                txtAddress.setText(foundCustomer.getAddress());
            } else {
                ValidationUtil.showWarning(this, "Customer not found with ID: "+ customerId, "Not Found");
            }
        }catch(Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String fullName = txtCustomerName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhoneNumber.getText().trim();
        String address = txtAddress.getText().trim();
        
        ValidationResult validation = ValidationUtil.validateCustomer(fullName, email, phone, address);
        
        if(!ValidationUtil.validateAndShow(this, validation)){
            return;
        }
        
        try{
            Customer customer = new Customer();
            customer.setFullName(fullName);
            customer.setEmail(email);
            customer.setPhone(phone);
            customer.setAddress(address);
            
            Integer customerId = customerService.addCustomer(customer);
            if(customerId != null && customerId > 0){
                ValidationUtil.showSuccess(this, "Customer added successfully!\n\n" + "Customer ID: "+ customerId + "\nName: "+ fullName);
                retrieveDataFromDB();
                refresh();
                
                if(salesPanel != null){
                    salesPanel.loadCustomerIdToCombo();
                }
            } else{
                ValidationUtil.showError(this, "Failed to add Customer. Please try again.", "Operation Failed");
            }
        } catch(Exception e){
            ValidationUtil.showError(this, "Error adding customer: "+ e.getMessage(), "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText().trim();
        
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Customer ID");
        if(!ValidationUtil.validateAndShow(this, idValidation)){
            ValidationUtil.showWarning(this, "Please search for a customer first using the Search field", "Search Required");
            txtSearch.requestFocus();
            return;
        }
        
        String fullName = txtCustomerName.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhoneNumber.getText().trim();
        String address = txtAddress.getText().trim();
        
        ValidationResult validation = ValidationUtil.validateCustomer(fullName, email, phone, address);
        
        if(!ValidationUtil.validateAndShow(this, validation)){
            return;
        }
        
        int customerId = Integer.parseInt(searchStr);
        
        try{
            Customer existingCustomer = customerService.findCustomerById(customerId);
            
            if(existingCustomer == null){
                ValidationUtil.showError(this, "Customer not found with ID: " + customerId, "Not Found");
                return;
            }
            
            existingCustomer.setFullName(fullName);
            existingCustomer.setEmail(email);
            existingCustomer.setPhone(phone);
            existingCustomer.setAddress(address);
            
            boolean updated = customerService.updateCustomer(existingCustomer);
            
            if(updated){
                ValidationUtil.showSuccess(this,
                        "Customer updated successfully!\n\n"+
                        "Customer: " + fullName + "\n" +
                        "Email: " + email + "\n" +
                        "Phone: " + phone);
                retrieveDataFromDB();
                refresh();
            } else{
                ValidationUtil.showError(this,
                        "Failed to Update customer. Please try again",
                        "Update Failed");
            }
            
        } catch(Exception e){
            ValidationUtil.showError(this,
                    "Error updating customer: " + e.getMessage(),
                    "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(isCashierMode){
            ValidationUtil.showWarning(this, "Access Denied\n\nOnly Admins can delete customers.", "Permission Denied");
            return;
        }
        
        // Get selected row from table
        int selectedRow = customerTable.getSelectedRow();
        
        if (selectedRow == -1) {
            ValidationUtil.showWarning(this,
                "Please select a customer from the table to delete",
                "No Selection");
            return;
        }
        
        // Get customer ID from selected row (column 0)
        int customerId = (int) customerTable.getValueAt(selectedRow, 0);
        String customerName = (String) customerTable.getValueAt(selectedRow, 1);
        
        try {
            // Show delete confirmation with customer details
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this customer?\n\n" +
                "Customer: " + customerName + "\n" +
                "ID: " + customerId + "\n\n" +
                "This action cannot be undone!",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            
            // Delete customer
            boolean deleted = customerService.deleteCustomer(customerId);
            
            if (deleted) {
                ValidationUtil.showSuccess(this, 
                    "Customer deleted successfully!\n\n" +
                    "Customer: " + customerName);
                
                retrieveDataFromDB();
                refresh();
            } else {
                ValidationUtil.showError(this, 
                    "Failed to delete customer.\n\n" +
                    "Possible reasons:\n" +
                    "• Customer has related sales records\n" +
                    "• Database constraint violation",
                    "Delete Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this, 
                "Error deleting customer: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable customerTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
