/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import service.EmployeeService;
import client.RMIClientManager;
import util.ValidationUtil;
import util.ValidationUtil.ValidationResult;
import util.PasswordUtil;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import java.awt.Frame;
import static util.PasswordUtil.hashPassword;

/**
 *
 * @author andyb
 */
public class EmployeePanel extends javax.swing.JPanel {
    
    private EmployeeService employeeService;
    DefaultTableModel tblModel = new DefaultTableModel();
    Employee currentEmployee;
    SalesPanel panel;  // FIX: Don't initialize here with null employee!
    

    /**
     * Creates new form ProductsPanel
     */
    public EmployeePanel(SalesPanel panel, Employee employee) {
        this.currentEmployee = employee;
        this.panel = panel;
        
        initComponents();
        
        try{
            employeeService = RMIClientManager.getInstance().getEmployeeService();
        }catch(Exception e){
            ValidationUtil.showError(this,
                    "Failed to connect to server: " + e.getMessage(),
                    "Connection Error");
            e.printStackTrace();
        }
        
        if(!employee.isAdmin()){
            showAccessDenied();
        } else{
            constructTableColumns();
            retrieveDataInTable();
        }
    }
    
    private void showAccessDenied(){
        removeAll();
        
        ValidationUtil.showWarning(this,
                "Access Denied\n\n" +
                "You do not have permission to access Employee Management.\n" +
                "This feature is only available to administrators.",
                "Access Denied");
    }
    
    public void setAdminMode(boolean isAdmin){
        if(isAdmin){
            System.out.println("Employee Panel: Admin Mode - full access");
        }
    }
    
    private void constructTableColumns(){
        tblModel.addColumn("Customer ID");
        tblModel.addColumn("Employee Name");
        tblModel.addColumn("Role");
        tblModel.addColumn("Salary");
        tblModel.addColumn("Hire Date");
        tblModel.addColumn("Contact");
        employeeTable.setModel(tblModel);
    }
    
    private void retrieveDataInTable(){
        tblModel.setRowCount(0);
        
        try{
            List<Employee> employees = employeeService.findAllEmployees();
            
            if(employees != null){
                for(Employee employee : employees){
                    tblModel.addRow(new Object[]{
                        employee.getEmployeeId(),
                        employee.getFullName(),
                        employee.getRole(),
                        employee.getSalary(),
                        employee.getHireDate(),
                        employee.getContact()
                    });
                }
            }
        } catch(Exception e){
            ValidationUtil.showError(this,
                "Error loading employees: " + e.getMessage(),
                "Database Error");
            e.printStackTrace();
        }
    }
    
    private void clearFields(){
        txtEmployeeName.setText("");
        txtContact.setText("");
        txtPassword.setText("");
        txtSalary.setText("");
        txtUsername.setText("");
        txtSearch.setText("");
        comboRole.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSalary = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        comboRole = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        profileBtn = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(50, 50, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Employee Management");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(160, 160, 160));
        jLabel10.setText("Full Name");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(160, 160, 160));
        jLabel12.setText("Email");

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Cashier" }));
        comboRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRoleActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(160, 160, 160));
        jLabel13.setText("Role");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(160, 160, 160));
        jLabel14.setText("Salary");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(160, 160, 160));
        jLabel1.setText("Password");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 160, 160));
        jLabel2.setText("Username");

        btnAdd.setBackground(new java.awt.Color(34, 197, 94));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(59, 130, 246));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(240, 240, 240));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(239, 68, 68));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(240, 240, 240));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel10)
                    .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboRole, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtContact, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(txtPassword))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsername)))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboRole)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtContact)))
                .addGap(40, 40, 40)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(employeeTable);

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(160, 160, 160));
        jLabel9.setText("Search By ID");

        btnSearch.setBackground(new java.awt.Color(100, 100, 100));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(240, 240, 240));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        profileBtn.setText("Profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profileBtn)
                        .addGap(31, 31, 31))
                    .addComponent(jScrollPane3))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(288, 288, 288)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(profileBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void comboRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRoleActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String fullName = txtEmployeeName.getText().trim();
        String role = comboRole.getSelectedItem().toString();
        String username = txtUsername.getText().trim();
        String salaryStr = txtSalary.getText().trim();
        String contact = txtContact.getText().trim();
        String password = String.valueOf(txtPassword.getPassword());
        
        ValidationResult salaryValidation = ValidationUtil.validateNumeric(salaryStr, "Salary");
        if (!ValidationUtil.validateAndShow(this, salaryValidation)) {
            txtSalary.requestFocus();
            return;
        }
        
        double salary = Double.parseDouble(salaryStr);
        
        ValidationResult validation = ValidationUtil.validateEmployee(
            fullName, role, username, salary, contact, password
        );
        
        if (!ValidationUtil.validateAndShow(this, validation)) {
            return;
        }
        
        try {
            Employee employee = new Employee();
            employee.setFullName(fullName);
            employee.setRole(role);
            employee.setUsername(username);
            employee.setSalary(salary);
            employee.setContact(contact);
            employee.setPasswordHash(password); 
            
            Integer employeeId = employeeService.addEmployee(employee);
            
            if (employeeId != null && employeeId > 0) {
                ValidationUtil.showSuccess(this,
                    "Employee added successfully!\n\n" +
                    "Employee ID: " + employeeId + "\n" +
                    "Name: " + fullName + "\n" +
                    "Username: " + username);
                
                retrieveDataInTable();
                clearFields();
                
                // Refresh employee list in SalesPanel if available
                if (panel != null) {
                    panel.loadEmployeeNameToCombo();
                }
            } else {
                ValidationUtil.showError(this,
                    "Failed to add employee. Please try again.",
                    "Operation Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error adding employee: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText().trim();
        
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Employee ID");
        if (!ValidationUtil.validateAndShow(this, idValidation)) {
            ValidationUtil.showWarning(this,
                "Please search for an employee first using the Search field",
                "Search Required");
            txtSearch.requestFocus();
            return;
        }
        
        String fullName = txtEmployeeName.getText().trim();
        String role = comboRole.getSelectedItem().toString();
        String username = txtUsername.getText().trim();
        String salaryStr = txtSalary.getText().trim();
        String contact = txtContact.getText().trim();
        String password = String.valueOf(txtPassword.getPassword());
        
        ValidationResult salaryValidation = ValidationUtil.validateNumeric(salaryStr, "Salary");
        if (!ValidationUtil.validateAndShow(this, salaryValidation)) {
            txtSalary.requestFocus();
            return;
        }
        
        double salary = Double.parseDouble(salaryStr);
        
        ValidationResult validation = ValidationUtil.validateEmployee(
            fullName, role, username, salary, contact, password
        );
        
        if (!ValidationUtil.validateAndShow(this, validation)) {
            return;
        }
        
        int employeeId = Integer.parseInt(searchStr);
        
        try {
            Employee existingEmployee = employeeService.findEmployeeById(employeeId);
            
            if (existingEmployee == null) {
                ValidationUtil.showError(this,
                    "Employee not found with ID: " + employeeId,
                    "Not Found");
                return;
            }
            
            existingEmployee.setFullName(fullName);
            existingEmployee.setRole(role);
            existingEmployee.setUsername(username);
            existingEmployee.setSalary(salary);
            existingEmployee.setContact(contact);
            existingEmployee.setPasswordHash(password);
            
            boolean updated = employeeService.updateEmployee(existingEmployee);
            
            if (updated) {
                ValidationUtil.showSuccess(this,
                    "Employee updated successfully!\n\n" +
                    "Employee: " + fullName + "\n" +
                    "Role: " + role + "\n" +
                    "Salary: RWF " + String.format("%,.2f", salary));
                
                retrieveDataInTable();
                clearFields();
            } else {
                ValidationUtil.showError(this,
                    "Failed to update employee. Please try again.",
                    "Update Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error updating employee: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText().trim();
        
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Employee ID");
        if (!ValidationUtil.validateAndShow(this, idValidation)) {
            txtSearch.requestFocus();
            return;
        }
        
        int employeeId = Integer.parseInt(searchStr);
        
        try {
            Employee foundEmployee = employeeService.findEmployeeById(employeeId);
            
            if (foundEmployee != null) {
                txtEmployeeName.setText(foundEmployee.getFullName());
                comboRole.setSelectedItem(foundEmployee.getRole());
                txtContact.setText(foundEmployee.getContact());
                txtSalary.setText(String.valueOf(foundEmployee.getSalary()));
                txtUsername.setText(foundEmployee.getUsername());
                txtPassword.setText("");
                
            } else {
                ValidationUtil.showWarning(this,
                    "Employee not found with ID: " + employeeId,
                    "Not Found");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error searching employee: " + e.getMessage(),
                "Search Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get selected row from table
        int selectedRow = employeeTable.getSelectedRow();
        
        if (selectedRow == -1) {
            ValidationUtil.showWarning(this,
                "Please select an employee from the table to delete",
                "No Selection");
            return;
        }
        
        // Get employee ID from selected row (column 0)
        int employeeId = (int) employeeTable.getValueAt(selectedRow, 0);
        String employeeName = (String) employeeTable.getValueAt(selectedRow, 1);
        String employeeRole = (String) employeeTable.getValueAt(selectedRow, 2);
        
        // Check if trying to delete self
        if (employeeId == currentEmployee.getEmployeeId()) {
            ValidationUtil.showWarning(this,
                "You cannot delete your own account!\n\n" +
                "Please ask another administrator to delete this account if needed.",
                "Cannot Delete Self");
            return;
        }
        
        try {
            // Show delete confirmation with employee details
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this employee?\n\n" +
                "Employee: " + employeeName + "\n" +
                "Role: " + employeeRole + "\n" +
                "ID: " + employeeId + "\n\n" +
                "This action cannot be undone!",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (confirm != JOptionPane.YES_OPTION) {
                return; // User cancelled
            }
            
            // Delete employee
            boolean deleted = employeeService.deleteEmployee(employeeId);
            
            if (deleted) {
                ValidationUtil.showSuccess(this,
                    "Employee deleted successfully!\n\n" +
                    "Employee: " + employeeName);
                
                retrieveDataInTable();
                clearFields();
            } else {
                ValidationUtil.showError(this,
                    "Failed to delete employee.\n\n" +
                    "Possible reasons:\n" +
                    "• Employee has related sales records\n" +
                    "• Employee has inventory transactions\n" +
                    "• Database constraint violation\n\n" +
                    "Consider deactivating the employee instead.",
                    "Delete Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error deleting employee: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = employeeTable.getSelectedRow();
        
        if(selectedRow == -1){
            ValidationUtil.showError(this, "Please select an employee from the table to view their profile", "No Employee Selected");
            return;
        }
        
        try{
            int employeeId = (int) employeeTable.getValueAt(selectedRow, 0);
            String employeeName = (String) employeeTable.getValueAt(selectedRow, 1);
            Employee selectedEmployee = employeeService.findEmployeeById(employeeId);
            
            if(selectedEmployee == null){
                ValidationUtil.showError(this,
                        "Employee data not found in database!\n\n" +
                        "Employee ID: " + employeeId + "\n" +
                        "Name: " + employeeName,
                        "Data Not found");
                return;
            }
            
            Frame parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);
            EmployeeProfilePanel profilePanel = new EmployeeProfilePanel(parentFrame, selectedEmployee, false);
            
            profilePanel.setVisible(true);
            retrieveDataInTable();
        } catch(Exception e){
            ValidationUtil.showError(this, "Error opening employee profile:\n\n" + e.getMessage(), "Profile Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_profileBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JTable employeeTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton profileBtn;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
