/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import service.ProductService;
import client.RMIClientManager;
import util.ValidationUtil;
import util.ValidationUtil.ValidationResult;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Employee;
import model.Product;

/**
 *
 * @author andyb
 */
public class ProductsPanel extends javax.swing.JPanel {
    
    private ProductService productService;
    
    DefaultTableModel tblModel = new DefaultTableModel();
    
    Employee currentEmployee;
    SalesPanel panel;  // FIX: Don't initialize here with null employee!
    private boolean isCashierMode = false;

    /**
     * Creates new form ProductsPanel
     */
    public ProductsPanel(SalesPanel panel,Employee employee) {
        this.currentEmployee = employee;
        this.panel = panel;
        
        initComponents();
        
        try{
            productService = RMIClientManager.getInstance().getProductService();
        }catch(Exception e){
            ValidationUtil.showError(this,
                "Failed to connect to server: " + e.getMessage(),
                "Connection Error");
            e.printStackTrace();
        }
        
        setupTable();
        populateTable();
        
    }
    
    private void setupTable(){
        tblModel.addColumn("Product ID");
        tblModel.addColumn("Product Name");
        tblModel.addColumn("Category");
        tblModel.addColumn("Price");
        tblModel.addColumn("Stock Quantity");
        tblModel.addColumn("Supplier");
        productTable.setModel(tblModel);
    }
    
    protected void populateTable(){
        tblModel.setRowCount(0);
        try{
            List<Product> products = productService.findAllProducts();
            
            if(products != null){
                for(Product theProduct : products){
                    tblModel.addRow(new Object[]{
                        theProduct.getProductId(),
                        theProduct.getProductName(),
                        theProduct.getCategory(),
                        String.format("%.2f", theProduct.getPrice()),
                        theProduct.getStockQuantity(),
                        theProduct.getSupplierName()
                    });
                }
            }
        } catch(Exception e){
            ValidationUtil.showError(this,
                "Error loading products: " + e.getMessage(),
                "Database Error");
            e.printStackTrace();
        }
    }
    
    private void clearFields(){
        txtCategory.setText("");
        txtPrice.setText("");
        txtProductName.setText("");
        txtSearch.setText("");
        txtStockQuantity.setText("");
        txtSupplierName.setText("");
    }
    
    public void setCashierMode(boolean isCashier){
        this.isCashierMode = isCashier;
        
        if(isCashier){
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(false);
            btnDelete.setEnabled(false);
            btnSearch.setEnabled(true);
            
            txtProductName.setEditable(false);
            txtPrice.setEditable(false);
            txtStockQuantity.setEditable(false);
            txtSupplierName.setEditable(false);
            txtCategory.setEditable(false);
            
            btnAdd.setBackground(new Color(100,100,100));
            btnUpdate.setBackground(new Color(100,100,100));
            btnDelete.setBackground(new Color(100,100,100));
            
            btnAdd.setToolTipText("Add Product - Admin Only");
            btnUpdate.setToolTipText("Update Product - Admin Only");
            btnDelete.setToolTipText("Delete Product - Admin Only");
        }
    }
    
    public void setAdminMode(boolean isAdmin) {
        if(isAdmin){
            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            btnSearch.setEnabled(true);
            
            txtProductName.setEditable(true);
            txtPrice.setEditable(true);
            txtStockQuantity.setEditable(true);
            txtSupplierName.setEditable(true);
            txtCategory.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtPrice = new javax.swing.JTextField();
        txtProductName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStockQuantity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCategory = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(50, 50, 50));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel8.setText("Product Management");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(160, 160, 160));
        jLabel3.setText("Product Name");

        txtStockQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStockQuantityActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(160, 160, 160));
        jLabel6.setText("Stock Quantity");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(160, 160, 160));
        jLabel7.setText("Supplier Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(160, 160, 160));
        jLabel2.setText("Price");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(160, 160, 160));
        jLabel5.setText("Category");

        btnAdd.setBackground(new java.awt.Color(34, 197, 94));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(240, 240, 240));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(59, 130, 246));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(240, 240, 240));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(239, 68, 68));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(240, 240, 240));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(100, 100, 100));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtStockQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(248, 248, 248))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtSupplierName)
                                        .addGap(113, 113, 113)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupplierName)
                            .addComponent(txtCategory))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(txtStockQuantity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(11, 11, 11))
        );

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(productTable);

        btnSearch.setBackground(new java.awt.Color(100, 100, 100));
        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(160, 160, 160));
        jLabel1.setText("Search Product By ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStockQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStockQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStockQuantityActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (isCashierMode) {
            ValidationUtil.showWarning(this,
                "Access Denied\n\nOnly Admins can add products",
                "Permission Denied");
            return;
        }
        
        // Get form data
        String productName = txtProductName.getText().trim();
        String category = txtCategory.getText().trim();
        String supplierName = txtSupplierName.getText().trim();
        String priceStr = txtPrice.getText().trim();
        String stockStr = txtStockQuantity.getText().trim();
        
        // ✅ Validate price is numeric
        ValidationResult priceValidation = ValidationUtil.validateNumeric(priceStr, "Price");
        if (!ValidationUtil.validateAndShow(this, priceValidation)) {
            txtPrice.requestFocus();
            return;
        }
        
        // ✅ Validate stock is integer
        ValidationResult stockValidation = ValidationUtil.validateInteger(stockStr, "Stock Quantity");
        if (!ValidationUtil.validateAndShow(this, stockValidation)) {
            txtStockQuantity.requestFocus();
            return;
        }
        
        double price = Double.parseDouble(priceStr);
        int stock = Integer.parseInt(stockStr);
        
        // ✅ Complete product validation
        ValidationResult validation = ValidationUtil.validateProduct(
            productName, category, price, stock
        );
        
        if (!ValidationUtil.validateAndShow(this, validation)) {
            return;
        }
        
        // All validations passed - proceed
        try {
            Product product = new Product();
            product.setProductName(productName);
            product.setCategory(category);
            product.setSupplierName(supplierName);
            product.setPrice(price);
            product.setStockQuantity(stock);
            
            Integer productId = productService.addProduct(product);
            
            if (productId != null && productId > 0) {
                ValidationUtil.showSuccess(this,
                    "Product added successfully!\n\n" +
                    "Product ID: " + productId + "\n" +
                    "Name: " + productName + "\n" +
                    "Price: RWF " + String.format("%,.2f", price));
                
                populateTable();
                clearFields();
                
                // Refresh product list in SalesPanel
                if (panel != null) {
                    panel.loadProductToCombo();
                }
            } else {
                ValidationUtil.showError(this,
                    "Failed to add product. Please try again.",
                    "Operation Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error adding product: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchStr = txtSearch.getText().trim();
        
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Product ID");
        if (!ValidationUtil.validateAndShow(this, idValidation)) {
            txtSearch.requestFocus();
            return;
        }
        
        int productId = Integer.parseInt(searchStr);
        
        try {
            Product foundProduct = productService.findProductById(productId);
            
            if (foundProduct != null) {
                txtProductName.setText(foundProduct.getProductName());
                txtCategory.setText(foundProduct.getCategory());
                txtPrice.setText(String.valueOf(foundProduct.getPrice()));
                txtSupplierName.setText(foundProduct.getSupplierName());
                txtStockQuantity.setText(String.valueOf(foundProduct.getStockQuantity()));
            } else {
                ValidationUtil.showWarning(this,
                    "Product not found with ID: " + productId,
                    "Not Found");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error searching product: " + e.getMessage(),
                "Search Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        if (isCashierMode) {
            ValidationUtil.showWarning(this,
                "Access Denied\n\nOnly Admins can update products",
                "Permission Denied");
            return;
        }
        
        String searchStr = txtSearch.getText().trim();
        
        // ✅ Validate product ID
        ValidationResult idValidation = ValidationUtil.validateInteger(searchStr, "Product ID");
        if (!ValidationUtil.validateAndShow(this, idValidation)) {
            ValidationUtil.showWarning(this,
                "Please search for a product first using the Search field",
                "Search Required");
            txtSearch.requestFocus();
            return;
        }
        
        // Get form data
        String productName = txtProductName.getText().trim();
        String category = txtCategory.getText().trim();
        String supplierName = txtSupplierName.getText().trim();
        String priceStr = txtPrice.getText().trim();
        String stockStr = txtStockQuantity.getText().trim();
        
        // ✅ Validate price
        ValidationResult priceValidation = ValidationUtil.validateNumeric(priceStr, "Price");
        if (!ValidationUtil.validateAndShow(this, priceValidation)) {
            txtPrice.requestFocus();
            return;
        }
        
        // ✅ Validate stock
        ValidationResult stockValidation = ValidationUtil.validateInteger(stockStr, "Stock Quantity");
        if (!ValidationUtil.validateAndShow(this, stockValidation)) {
            txtStockQuantity.requestFocus();
            return;
        }
        
        double price = Double.parseDouble(priceStr);
        int stock = Integer.parseInt(stockStr);
        
        // ✅ Complete validation
        ValidationResult validation = ValidationUtil.validateProduct(
            productName, category, price, stock
        );
        
        if (!ValidationUtil.validateAndShow(this, validation)) {
            return;
        }
        
        int productId = Integer.parseInt(searchStr);
        
        try {
            Product product = new Product();
            product.setProductId(productId);
            product.setProductName(productName);
            product.setCategory(category);
            product.setPrice(price);
            product.setStockQuantity(stock);
            product.setSupplierName(supplierName);
            
            boolean updated = productService.updateProduct(product);
            
            if (updated) {
                ValidationUtil.showSuccess(this,
                    "Product updated successfully!\n\n" +
                    "Product: " + productName + "\n" +
                    "Price: RWF " + String.format("%,.2f", price) + "\n" +
                    "Stock: " + stock + " units");
                
                populateTable();
                clearFields();
            } else {
                ValidationUtil.showError(this,
                    "Failed to update product. Product may not exist.",
                    "Update Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error updating product: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (isCashierMode) {
            ValidationUtil.showWarning(this,
                "Access Denied\n\nOnly Admins can delete products",
                "Permission Denied");
            return;
        }
        
        // Get selected row from table
        int selectedRow = productTable.getSelectedRow();
        
        if (selectedRow == -1) {
            ValidationUtil.showWarning(this,
                "Please select a product from the table to delete",
                "No Selection");
            return;
        }
        
        // Get product ID from selected row (column 0)
        int productId = (int) productTable.getValueAt(selectedRow, 0);
        String productName = (String) productTable.getValueAt(selectedRow, 1);
        
        try {
            // Get product details
            Product product = productService.findProductById(productId);
            
            if (product == null) {
                ValidationUtil.showError(this,
                    "Product not found with ID: " + productId + "\n\n" +
                    "The product may have been deleted by another user.",
                    "Not Found");
                return;
            }
            
            // Show delete confirmation with product details
            int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this product?\n\n" +
                "Product: " + productName + "\n" +
                "Stock: " + product.getStockQuantity() + " units\n" +
                "Price: RWF " + String.format("%.2f", product.getPrice()) + "\n" +
                "ID: " + productId + "\n\n" +
                "This action cannot be undone!",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);
            
            if (confirm != JOptionPane.YES_OPTION) {
                return;
            }
            
            // Delete product
            boolean deleted = productService.deleteProduct(productId);
            
            if (deleted) {
                ValidationUtil.showSuccess(this,
                    "Product deleted successfully!\n\n" +
                    "Product: " + productName);
                
                populateTable();
                clearFields();
            } else {
                ValidationUtil.showError(this,
                    "Failed to delete product.\n\n" +
                    "Possible reasons:\n" +
                    "• Product has related sales records\n" +
                    "• Product has inventory transactions\n" +
                    "• Database constraint violation",
                    "Delete Failed");
            }
        } catch (Exception e) {
            ValidationUtil.showError(this,
                "Error deleting product: " + e.getMessage(),
                "Server Error");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productTable;
    private javax.swing.JTextField txtCategory;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtProductName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStockQuantity;
    private javax.swing.JTextField txtSupplierName;
    // End of variables declaration//GEN-END:variables
}
