/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import model.Employee;

/**
 *
 * @author andyb
 */
public class SplashScreenPanel extends javax.swing.JFrame {
    
    private Employee currentEmployee;
    
    private static final Color DARK_BG = new Color(30, 30, 30);
    private static final Color ACCENT_TEAL = new Color(20, 184, 166);
    private static final Color TEXT_PRIMARY = new Color(240, 240, 240);
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SplashScreenPanel.class.getName());

    /**
     * Creates new form SplashScreenPanel
     */
    public SplashScreenPanel() {
        
        
        initComponents();
        setLocationRelativeTo(null);
        progressBar.setBorder(BorderFactory.createLineBorder(ACCENT_TEAL, 2));
        startProgress();
    }
    
    private void startProgress(){
        Timer timer = new Timer(30, null);
        timer.addActionListener(new ActionListener(){
            int progress = 0;

            @Override
            public void actionPerformed(ActionEvent e) {
                progressBar.setValue(progress);
                progress++;
                if (progress > 100){
                    timer.stop();
                    dispose();
                    
                    LoginPageWithOTP login = new LoginPageWithOTP();
                    login.setVisible(true);
                }
            }
            
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        loadingLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(600, 300));
        setResizable(false);

        panel.setBackground(new java.awt.Color(30, 30, 30));
        panel.setLayout(new java.awt.BorderLayout());

        logoLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(20, 184, 166));
        logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoLabel.setText("Epignosis Supermarket");
        panel.add(logoLabel, java.awt.BorderLayout.CENTER);

        loadingLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        loadingLabel.setForeground(new java.awt.Color(240, 240, 240));
        loadingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingLabel.setText("Loading Supermarket Management System...");
        panel.add(loadingLabel, java.awt.BorderLayout.PAGE_START);

        progressBar.setBackground(new java.awt.Color(30, 30, 30));
        progressBar.setForeground(new java.awt.Color(20, 184, 166));
        progressBar.setPreferredSize(new java.awt.Dimension(500, 25));
        progressBar.setStringPainted(true);
        panel.add(progressBar, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new SplashScreenPanel().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadingLabel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
