package service;

import java.rmi.Remote;
import java.rmi.RemoteException;
import java.util.List;
import model.Employee;
import model.EmployeeProfile;

/**
 * Employee Service RMI Interface - COMPLETE VERSION
 * Defines all remote methods for employee management
 */
public interface EmployeeService extends Remote {
    
    // ========== AUTHENTICATION ==========
    
    /**
     * Authenticate employee with username and password
     * @param username Employee username
     * @param password Plain text password
     * @return Employee object if authentication successful, null otherwise
     */
    Employee authenticate(String username, String password) throws RemoteException;
    
    // ========== BASIC CRUD ==========
    
    /**
     * Find employee by ID
     * @param employeeId Employee ID
     * @return Employee object or null if not found
     */
    Employee findEmployeeById(int employeeId) throws RemoteException;
    
    /**
     * Find employee by username
     * @param username Employee username
     * @return Employee object or null if not found
     */
    Employee findByUsername(String username) throws RemoteException;
    
    /**
     * Get all employees
     * @return List of all employees
     */
    List<Employee> findAllEmployees() throws RemoteException;
    
    /**
     * Add new employee
     * @param employee Employee object to add
     * @return Generated employee ID if successful, null otherwise
     */
    Integer addEmployee(Employee employee) throws RemoteException;
    
    /**
     * Update existing employee
     * @param employee Employee object with updated data
     * @return true if successful, false otherwise
     */
    boolean updateEmployee(Employee employee) throws RemoteException;
    
    // ========== SEARCH & FILTER ==========
    
    /**
     * Find employees by role
     * @param role Role to search for (Admin, Manager, Cashier)
     * @return List of employees with the specified role
     */
    List<Employee> findEmployeesByRole(String role) throws RemoteException;
    
    /**
     * Search employees by name
     * @param searchTerm Search term to match against full name
     * @return List of employees matching the search term
     */
    List<Employee> searchEmployeesByName(String searchTerm) throws RemoteException;
    
    /**
     * Get active employees only (excludes deactivated)
     * @return List of active employees
     */
    List<Employee> findActiveEmployees() throws RemoteException;
    
    /**
     * Get count of all employees
     * @return Total number of employees
     */
    Long getTotalEmployeeCount() throws RemoteException;
    
    /**
     * Get count of employees by role
     * @param role Role to count
     * @return Number of employees with specified role
     */
    Long getEmployeeCountByRole(String role) throws RemoteException;
    
    // ========== DELETE METHODS ==========
    
    /**
     * Delete employee (with validation - checks for dependencies)
     * @param employeeId Employee ID to delete
     * @return true if deleted, false if has dependencies or not found
     */
    boolean deleteEmployee(int employeeId) throws RemoteException;
    
    /**
     * Deactivate employee (soft delete - preserves history)
     * @param employeeId Employee ID to deactivate
     * @return true if deactivated, false otherwise
     */
    boolean deactivateEmployee(int employeeId) throws RemoteException;
    
    /**
     * Force delete employee (ignores dependencies - CASCADE delete)
     * WARNING: Use with extreme caution!
     * @param employeeId Employee ID to force delete
     * @return true if deleted, false otherwise
     */
    boolean forceDeleteEmployee(int employeeId) throws RemoteException;
    
    /**
     * Check if employee can be safely deleted
     * @param employeeId Employee ID to check
     * @return true if safe to delete (no dependencies), false otherwise
     */
    boolean canDeleteEmployee(int employeeId) throws RemoteException;
    
    /**
     * Reactivate a deactivated employee
     * @param employeeId Employee ID to reactivate
     * @return true if reactivated, false otherwise
     */
    boolean reactivateEmployee(int employeeId) throws RemoteException;
    
    // ========== STATISTICS & REPORTING ==========
    
    /**
     * Get total sales count by employee
     * @param employeeId Employee ID
     * @return Number of sales made by this employee
     */
    Long getEmployeeSalesCount(int employeeId) throws RemoteException;
    
    /**
     * Get total revenue generated by employee
     * @param employeeId Employee ID
     * @return Total revenue amount
     */
    Double getEmployeeTotalRevenue(int employeeId) throws RemoteException;
    
    /**
     * Get inventory transaction count by employee
     * @param employeeId Employee ID
     * @return Number of inventory transactions
     */
    Long getEmployeeTransactionCount(int employeeId) throws RemoteException;
    
    /**
     * Get employee performance summary
     * @param employeeId Employee ID
     * @return String summary of sales count, revenue, etc.
     */
    String getEmployeePerformanceSummary(int employeeId) throws RemoteException;
    
    // ========== PROFILE METHODS ==========
    
    /**
     * Get employee profile
     * @param employeeId Employee ID
     * @return EmployeeProfile object or null if not found
     */
    EmployeeProfile getEmployeeProfile(int employeeId) throws RemoteException;
    
    /**
     * Save or update employee profile
     * @param profile EmployeeProfile object to save
     * @return true if saved, false otherwise
     */
    boolean saveEmployeeProfile(EmployeeProfile profile) throws RemoteException;
    
    /**
     * Change employee password
     * @param employeeId Employee ID
     * @param oldPassword Current password (for verification)
     * @param newPassword New password
     * @return true if changed, false if old password incorrect or error
     */
    boolean changePassword(int employeeId, String oldPassword, String newPassword) throws RemoteException;
    
    /**
     * Mark first login as complete
     * @param employeeId Employee ID
     * @return true if updated, false otherwise
     */
    boolean markFirstLoginComplete(int employeeId) throws RemoteException;
    
    /**
     * Check if employee needs to complete first login
     * @param employeeId Employee ID
     * @return true if first login not complete, false otherwise
     */
    boolean isFirstLogin(int employeeId) throws RemoteException;
    
    // ========== VALIDATION ==========
    
    /**
     * Check if username is available
     * @param username Username to check
     * @return true if available, false if already taken
     */
    boolean isUsernameAvailable(String username) throws RemoteException;
    
    /**
     * Check if username is available (excluding specific employee ID)
     * Used when updating employee to allow keeping same username
     * @param username Username to check
     * @param excludeEmployeeId Employee ID to exclude from check
     * @return true if available, false if taken by another employee
     */
    boolean isUsernameAvailable(String username, int excludeEmployeeId) throws RemoteException;
}
