package util;

import com.opencsv.CSVWriter;
import model.ReportData;
import java.io.ByteArrayOutputStream;
import java.io.OutputStreamWriter;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author andyb
 */
public class CSVReportGenerator {
    
    public static byte[] generateCSV(ReportData reportData) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        OutputStreamWriter osw = new OutputStreamWriter(baos);
        CSVWriter writer = new CSVWriter(osw);
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy HH:mm");
        
        // Add Title
        writer.writeNext(new String[]{reportData.getReportTitle()});
        writer.writeNext(new String[]{""}); // Empty line
        
        // Add Report Info
        writer.writeNext(new String[]{"Generated:", sdf.format(reportData.getGeneratedDate())});
        writer.writeNext(new String[]{"Generated By:", reportData.getGeneratedBy()});
        
        if (reportData.getStartDate() != null) {
            writer.writeNext(new String[]{
                "Period:", 
                sdf.format(reportData.getStartDate()) + " - " + sdf.format(reportData.getEndDate())
            });
        }
        
        writer.writeNext(new String[]{""}); // Empty line
        
        // Add Headers
        List<String[]> headers = reportData.getHeaders();
        if (headers != null && !headers.isEmpty()) {
            writer.writeNext(headers.get(0));
        }
        
        // Add Data
        List<List<String>> data = reportData.getData();
        for (List<String> row : data) {
            writer.writeNext(row.toArray(new String[0]));
        }
        
        // Add Summary
        if (reportData.getSummary() != null && !reportData.getSummary().isEmpty()) {
            writer.writeNext(new String[]{""}); // Empty line
            writer.writeNext(new String[]{reportData.getSummary()});
        }
        
        writer.close();
        
        return baos.toByteArray();
    }
    
}
