package util;

import model.ReportData;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.*;
import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author andyb
 */
public class ExcelReportGenerator {
    
     public static byte[] generateExcel(ReportData reportData) throws Exception {
        XSSFWorkbook workbook = new XSSFWorkbook();
        XSSFSheet sheet = workbook.createSheet(reportData.getReportType());
        
        int rowNum = 0;
        
        // Create styles
        CellStyle titleStyle = createTitleStyle(workbook);
        CellStyle headerStyle = createHeaderStyle(workbook);
        CellStyle dataStyle = createDataStyle(workbook);
        CellStyle altRowStyle = createAltRowStyle(workbook);
        
        // Add Title
        Row titleRow = sheet.createRow(rowNum++);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue(reportData.getReportTitle());
        titleCell.setCellStyle(titleStyle);
        
        // Add Report Info
        SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy HH:mm");
        rowNum++; // Skip a row
        
        Row infoRow1 = sheet.createRow(rowNum++);
        infoRow1.createCell(0).setCellValue("Generated:");
        infoRow1.createCell(1).setCellValue(sdf.format(reportData.getGeneratedDate()));
        
        Row infoRow2 = sheet.createRow(rowNum++);
        infoRow2.createCell(0).setCellValue("Generated By:");
        infoRow2.createCell(1).setCellValue(reportData.getGeneratedBy());
        
        if (reportData.getStartDate() != null) {
            Row infoRow3 = sheet.createRow(rowNum++);
            infoRow3.createCell(0).setCellValue("Period:");
            infoRow3.createCell(1).setCellValue(
                sdf.format(reportData.getStartDate()) + " - " + 
                sdf.format(reportData.getEndDate())
            );
        }
        
        rowNum++; // Skip a row
        
        // Add Headers
        List<String[]> headers = reportData.getHeaders();
        if (headers != null && !headers.isEmpty()) {
            Row headerRow = sheet.createRow(rowNum++);
            int colNum = 0;
            for (String header : headers.get(0)) {
                Cell cell = headerRow.createCell(colNum++);
                cell.setCellValue(header);
                cell.setCellStyle(headerStyle);
            }
        }
        
        // Add Data
        List<List<String>> data = reportData.getData();
        boolean altRow = false;
        for (List<String> rowData : data) {
            Row row = sheet.createRow(rowNum++);
            int colNum = 0;
            for (String cellData : rowData) {
                Cell cell = row.createCell(colNum++);
                cell.setCellValue(cellData);
                cell.setCellStyle(altRow ? altRowStyle : dataStyle);
            }
            altRow = !altRow;
        }
        
        // Add Summary
        if (reportData.getSummary() != null && !reportData.getSummary().isEmpty()) {
            rowNum++;
            Row summaryRow = sheet.createRow(rowNum);
            summaryRow.createCell(0).setCellValue(reportData.getSummary());
        }
        
        // Auto-size columns
        for (int i = 0; i < (headers != null && !headers.isEmpty() ? headers.get(0).length : 0); i++) {
            sheet.autoSizeColumn(i);
        }
        
        // Write to byte array
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        workbook.write(baos);
        workbook.close();
        
        return baos.toByteArray();
    }
    
    private static CellStyle createTitleStyle(XSSFWorkbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 16);
        style.setFont(font);
        return style;
    }
    
    private static CellStyle createHeaderStyle(XSSFWorkbook workbook) {
        CellStyle style = workbook.createCellStyle();
        Font font = workbook.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());
        style.setFont(font);
        style.setFillForegroundColor(new XSSFColor(new byte[]{20, (byte)184, (byte)166}));
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        return style;
    }
    
    private static CellStyle createDataStyle(XSSFWorkbook workbook) {
        CellStyle style = workbook.createCellStyle();
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        return style;
    }
    
    private static CellStyle createAltRowStyle(XSSFWorkbook workbook) {
        CellStyle style = createDataStyle(workbook);
        style.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        return style;
    }
    
}
