package util;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import model.ReportData;
import java.io.ByteArrayOutputStream;
import java.text.SimpleDateFormat;
import java.util.List;

/**
 *
 * @author andyb
 */
public class PDFReportGenerator {
    
    private static final Font TITLE_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, BaseColor.DARK_GRAY);
    private static final Font HEADER_FONT = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.WHITE);
    private static final Font NORMAL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);
    private static final Font SMALL_FONT = FontFactory.getFont(FontFactory.HELVETICA, 8, BaseColor.GRAY);
    
    private static final BaseColor HEADER_BG = new BaseColor(20, 184, 166); // Teal
    private static final BaseColor ALT_ROW_BG = new BaseColor(240, 240, 240);
    
    public static byte[] generatePDF(ReportData reportData) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Document document = new Document(PageSize.A4);
        
        try {
            PdfWriter.getInstance(document, baos);
            document.open();
            
            // Add Title
            Paragraph title = new Paragraph(reportData.getReportTitle(), TITLE_FONT);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(10);
            document.add(title);
            
            // Add Report Info
            SimpleDateFormat sdf = new SimpleDateFormat("dd MMM yyyy HH:mm");
            Paragraph info = new Paragraph();
            info.setFont(SMALL_FONT);
            info.add("Generated: " + sdf.format(reportData.getGeneratedDate()) + "\n");
            info.add("Generated By: " + reportData.getGeneratedBy() + "\n");
            if (reportData.getStartDate() != null) {
                info.add("Period: " + sdf.format(reportData.getStartDate()) + 
                        " - " + sdf.format(reportData.getEndDate()) + "\n");
            }
            info.setSpacingAfter(15);
            document.add(info);
            
            // Add Table
            List<String[]> headers = reportData.getHeaders();
            List<List<String>> data = reportData.getData();
            
            if (headers != null && !headers.isEmpty()) {
                PdfPTable table = new PdfPTable(headers.get(0).length);
                table.setWidthPercentage(100);
                
                // Add Headers
                for (String header : headers.get(0)) {
                    PdfPCell cell = new PdfPCell(new Phrase(header, HEADER_FONT));
                    cell.setBackgroundColor(HEADER_BG);
                    cell.setPadding(8);
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    table.addCell(cell);
                }
                
                // Add Data Rows
                boolean altRow = false;
                for (List<String> row : data) {
                    for (String cellData : row) {
                        PdfPCell cell = new PdfPCell(new Phrase(cellData, NORMAL_FONT));
                        if (altRow) {
                            cell.setBackgroundColor(ALT_ROW_BG);
                        }
                        cell.setPadding(6);
                        table.addCell(cell);
                    }
                    altRow = !altRow;
                }
                
                document.add(table);
            }
            
            // Add Summary if exists
            if (reportData.getSummary() != null && !reportData.getSummary().isEmpty()) {
                Paragraph summary = new Paragraph("\n" + reportData.getSummary(), NORMAL_FONT);
                summary.setSpacingBefore(15);
                document.add(summary);
            }
            
            // Add Footer
            Paragraph footer = new Paragraph(
                "\n\nEpignosis Supermarket Management System", 
                SMALL_FONT
            );
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);
            
        } finally {
            document.close();
        }
        
        return baos.toByteArray();
        
    }
}